# Generated by Django 4.1.7 on 2023-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('populacao', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('sigla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
    ]
